### ISSUE TITLE
Hi I git clone the master but run into problems during the compiling.

### ISSUE THREAD

**Issue by PlantMaize** [Plant-Root-Soil-Interactions-Modelling/CRootBox#1]
Hi I git clone the master but run into problems during the compiling.
I use Ubuntu 16.04 and cloned it under my home path.
I cd into the /CRootBox path, but when I run `g++ *.cpp -std=c++11` the error below comes out.

>`In file included from /usr/local/include/boost/python/detail/prefix.hpp:13:0,
>from /usr/local/include/boost/python/args.hpp:8,

>from /usr/local/include/boost/python.hpp:11,

>from PythonRootSystem.cpp:20:

>/usr/local/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
>compilation terminated.`

**Comment by xiaoranzhou** [comment]
There could be some problems around the python installation or boost package.

But the **easy** solution is to comment the line 16 in File PythonRootSystem.cpp
 `#define PYTHON_WRAPPER // UNCOMMENT TO BUILD SHARED LIBRARY`
aka to put "//" before the line.

This is working at least if you only want to compile it by c++ without python biding and I only tried example1a.

If you want to use the example1a.py files, please follow the "python building guide.txt"
