### ISSUE TITLE
Error runing CRootBox

### ISSUE THREAD

**Issue by AnaPG2018** [Plant-Root-Soil-Interactions-Modelling/CRootBox#12]
Hi!!
I have this error when I try to run my rparm in CRootBox:
"Read 3 root type parameters
Basal root type #4 was not defined, using tap root parameters instead
Shootborne root type #5 was not defined, using tap root parameters instead"

I copy below my rparam code for you to check what could be wrong with it:

# Parameter set for type
type	1
name	PR
lb	1.0798	6.18
la	4.703	1.09012
ln	0.50	0.0377
lmax	48.104	0.9426
r	2.34	0.31
a	0.05	0.005
color	1	0.1	0
tropism	1	0.5	0.2
dx	1
successors	2	2	3
successorP	2	0.8 0.2
theta	0.78	0.436332
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	2
name	1storderlateral
lb	5.21	4.54
la	0.56	0.061
ln	0.886	0.77
lmax	3.80189	3.2353
r	0.6911	0.528
a	0.03	0.003
color	1	1	0
tropism	1	10	0.4
dx	1
successors	1	3
successorP	1	1
theta	47.672	17.5986
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	3
name	2ndorderlateral
lb	6.941	3.68
la	0	0.0
ln	0.0	0.0
lmax	6.941	3.68
r	1.3882	0.7365
a	0.02	0.002
color	1	1	1
tropism	1	10	0.4
dx	1
successors	0	0
successorP	0	0
theta	31.9611	16.2099
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	4
name	Basal
lb	12.00	2.67
la	4.58	0.98
ln	1.56	0.95
lmax	40.217	7.35
r	1.98	0.14
a	0.03	0.003
color	1	1	0
tropism	1	1	0.2
dx	1
successors	1	2
successorP	1	1
theta	50.93	12.94
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	5
name	SBroot
lb	9.82	2.3
la	4.53	3.30
ln	1.6780	0.0
lmax	40.4656	3.938
r	0.39	0.106
a	0.03	0.003
color	1	1	0
tropism	1	10	0.3
dx	1
successors	1	2
successorP	1	1
theta	36.72591	17.48195
rlt	1000000000	100000000
gf	1

Thanks for your help!
Ana

**Comment by xiaoranzhou** [comment]
Hi AnaPG2018, sorry for the delay of the reply. Have you solve the problem?
I guess the problem could be the successor in parameter type 3 where you put two "0" on each line. Which is not necessary. So I changed them to one “0” then the parameters are read as normal.
Here is the revised code just in case
```
# Parameter set for type
type	1
name	PR
lb	1.0798	6.18
la	4.703	1.09012
ln	0.50	0.0377
lmax	48.104	0.9426
r	2.34	0.31
a	0.05	0.005
color	1	0.1	0
tropism	1	0.5	0.2
dx	1
successors	2	2	3
successorP	2	0.8 0.2
theta	0.78	0.436332
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	2
name	1storderlateral
lb	5.21	4.54
la	0.56	0.061
ln	0.886	0.77
lmax	3.80189	3.2353
r	0.6911	0.528
a	0.03	0.003
color	1	1	0
tropism	1	10	0.4
dx	1
successors	1	3
successorP	1	1
theta	47.672	17.5986
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	3
name	2ndorderlateral
lb	6.941	3.68
la	0	0.0
ln	0.0	0.0
lmax	6.941	3.68
r	1.3882	0.7365
a	0.02	0.002
color	1	1	1
tropism	1	10	0.4
dx	1
successors	0	
successorP	0	
theta	31.9611	16.2099
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	4
name	Basal
lb	12.00	2.67
la	4.58	0.98
ln	1.56	0.95
lmax	40.217	7.35
r	1.98	0.14
a	0.03	0.003
color	1	1	0
tropism	1	1	0.2
dx	1
successors	1	2
successorP	1	1
theta	50.93	12.94
rlt	1000000000	100000000
gf	1
# Parameter set for type
type	5
name	SBroot
lb	9.82	2.3
la	4.53	3.30
ln	1.6780	0.0
lmax	40.4656	3.938
r	0.39	0.106
a	0.03	0.003
color	1	1	0
tropism	1	10	0.3
dx	1
successors	1	2
successorP	1	1
theta	36.72591	17.48195
rlt	1000000000	100000000
gf	1
```
