### ISSUE TITLE
Python ToolBox

### ISSUE THREAD

**Issue by sathyanarayanrao** [Plant-Root-Soil-Interactions-Modelling/CRootBox#13]
Hello CRootBox team,

I could not succeed in building a python shared library using the python building guide.txt 

The first line : 

1. comment line 16 "// #define PYTHON_WRAPPER ..."

### I could not find such a line in main.cpp at line 16. Can you please help. 

2. compile the CRootBox model with the following command line

   g++ examples/Exudation/gauss_legendre.cpp *.cpp -std=c++11 -c -fpic 

3. outcomment line 16 again

4. g++ -std=c++11 -O3 -fpic -shared -o py_rootbox.so -Wl,-soname,"py_rootbox.so" PythonRootSystem.cpp -I/usr/include/python3.4 -lboost_python-py34 ModelParameter.o Root.o RootSystem.o analysis.o sdf.o tropism.o gauss_legendre.o

### How do I change the step 4 to python 3.6, just change py34 to py36 ? 

- /usr/include/python3.4    is the path to the file pyconfig.h
- boost_python needs to be installed, there will be a file /usr/lib/x86_64-linux-gnu/libboost_python-py34.so

**Comment by xiaoranzhou** [comment]
Hi sathyanarayanrao, 

## 1. first question
I could not find such a line in main.cpp at line 16. Can you please help.
the line 16 is the line in file PythonRootSystem.cpp, if you dont need python binding, you can just comment it, and run the a.out file.

## 2. second question 
How do I change the step 4 to python 3.6, just change py34 to py36 ?
it depends on the python path you have. 
you can also use cmake to build the python binding, which should be easier for linux user. 
```
# build the CRootBox library using CMake
# Simply type cmake . && make
# although out-of-source-builds are encouraged
```

if you are using windows you can also follow the guide here https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox#boostpython-binding-guide-in-windows

**Comment by xiaoranzhou** [comment]
Issue closed because no more (negative) feedback

**Comment by sathyanarayanrao** [comment]
Thank you xiaoranzhou. I have one more question. I modified an example (example_maize.h) to include the rhizotron but somehow it doesn't recognize the SDF_PlantBox rhizotron command. 

Even though I have  `SDF_PlantBox rhizotron(1.4,27,27)`;, I still see rootsystem has spread out as if there is no rhizotron (attached) 
[rootsystem.txt]

(https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/files/2075378/rootsystem.txt)


Are there any examples of using a rectangular rhizotron in C-RootBox ? If yes, please let me know. 


```
using namespace std;

void example_maize()
{
    RootSystem rootsystem;

    string name = "Zea_maize";


    /*
     * Open plant and root parameter from a file
     */
    rootsystem.openFile(name);
    //rootsystem.writeParameters(std::cout);

    //RootSystemParameter::write(std::cout);
    SDF_PlantBox rhizotron(1.4,27,27);
    /*
     * Initialize
     */
    rootsystem.initialize();
    
    /*
     * Simulate
     */

    //double simtime = 60; // 20, 40, 60 days
    
    double simtime=rootsystem.rsparam_pub.simtime;
    double dt = rootsystem.rsparam_pub.dt;    

    //double simtime = rtparam
    //double dt = simtime; // try other values here
    
    int N = round(simtime/dt);

    for (int i=0; i<N; i++) {
        rootsystem.simulate(dt);
	rootsystem.write("out/rootsystem"+std::to_string(i+1)+".vtp");
	SegmentAnalyser analysis(rootsystem);
	analysis.write("out/rootsystem"+std::to_string(i+1)+".rswms");
    }
```

**Comment by xiaoranzhou** [comment]
Hi sathyanarayanrao,

After you define the SDF_PlantBox you need to use other functions to apply it. For example.
`// 1.creates a cylindrical soil core with top radius 5 cm, bot radius 5 cm, height 50cm, not square but circular
    SDF_PlantContainer soilcore(5,5,40,false);

    //2. creates a square 27*27 cm containter with height 1.5 cm (used in parametrisation experiment)
    SDF_PlantBox rhizotron(1.4,27,27);

    //3. creates a square rhizotron r*r, with height h, rotated around the x-axis for angle alpha
    double r = 20;
    double h = 4;
    double alpha = 45.;
    SDF_PlantContainer rhizotron2(r,r,h,true);
    Vector3d posA = Vector3d(0,r,-h/2); // origin before rotation
    Matrix3d A = Matrix3d::rotX(alpha/180.*3.14);
    posA = A.times(posA); // origin after rotation
    SDF_RotateTranslate rotatedRhizotron(&rhizotron2,alpha,0,posA.times(-1));

    //rootsystem.setGeometry(&soilcore); // pick one of the geometries
    rootsystem.setGeometry(&rhizotron); // pick one of the geometries
    //rootsystem.setGeometry(&rotatedRhizotron); // pick one of the geometries
`

They are actually in example2.h
https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/blob/master/examples/example2.h here
