### ISSUE TITLE
RootSys Format

### ISSUE THREAD

**Issue by sathyanarayanrao** [Plant-Root-Soil-Interactions-Modelling/CRootBox#14]
Dear CRootbox team,

It is nice that I can try CRootbox online and download it in different format. But on my computer, I 
was unable to get RootSys format file. 

I am running example4.h and experimenting different output format as in the "Try it online" version of CRootbox. 

Using 

```
rootsystem.write(name+".rsml") ;
SegmentAnalyser analysis(rootsystem);
analysis.write("rootsystem.txt");
```

I could get the csv and rsml format, but I get error when I try RootSys format. Can you please tell me how can I output rootsystem in RootSys format as in the online version ?

**Comment by DanielLeitner** [comment]
Hello, I am afraid that is not implemented in CRootbox, only in the shinyapp web applicaiton
