### ISSUE TITLE
Large files in the repository limit usability

### ISSUE THREAD

**Issue by timokoch** [Plant-Root-Soil-Interactions-Modelling/CRootBox#15]
There have been some large files added to the repository which don't add functionality.
There is git-lfs for that https://help.github.com/articles/configuring-git-large-file-storage/

**Comment by timokoch** [comment]
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File publication archive/VZJ 2018/Analysis.ipynb is 54.29 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File publication archive/VZJ 2018/S1 Complete Analysis.pdf is 70.13 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

**Comment by DanielLeitner** [comment]
thanks for the comment! we reduced the size

**Comment by schnepfa** [comment]
You may also only download the master branch instead of the whole repository: 
git clone -b master --single-branch https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox.git

**Comment by HieuMaiTrung** [comment]
This issue seems still there
```
git clone -b master --single-branch https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox.git
Cloning into 'CRootBox'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2083 (delta 0), reused 0 (delta 0), pack-reused 2081
Receiving objects: 100% (2083/2083), 208.66 MiB | 29.30 MiB/s, done.
Resolving deltas: 100% (1308/1308), done.
Checking out files: 100% (308/308), done.
```
200+MB is too large
