### ISSUE TITLE
While using python building error occurs

### ISSUE THREAD

**Issue by PlantMaize** [Plant-Root-Soil-Interactions-Modelling/CRootBox#2]
Hi when I type `python example1a.py` the following error occurred.
`Traceback (most recent call last):
File "example1a.py", line 1, in <module>
import py_rootbox as rb
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0: undefined symbol: PyUnicode_AsUTF8String`

**Comment by xiaoranzhou** [comment]
Good day, it is better to install python3.5 or python3.4, and use `python3.4 example1a.py` to run the python code.

if you installed python3.5, please change the 3.4 and 34 in the code of "python building guide.txt" as well. for example:
from line 10
`4. g++ -std=c++11 -O3 -fpic -shared -o py_rootbox.so -Wl,-soname,"py_rootbox.so" PythonRootSystem.cpp -I/usr/include/python**3.4** -lboost_python-py**34** ModelParameter.o Root.o RootSystem.o analysis.o sdf.o tropism.o gauss_legendre.o`
to 
`4. g++ -std=c++11 -O3 -fpic -shared -o py_rootbox.so -Wl,-soname,"py_rootbox.so" PythonRootSystem.cpp -I/usr/include/python**3.5** -lboost_python-py**35** ModelParameter.o Root.o RootSystem.o analysis.o sdf.o tropism.o gauss_legendre.o`
