### ISSUE TITLE
./test_crootbox failed

### ISSUE THREAD

**Issue by HieuMaiTrung** [Plant-Root-Soil-Interactions-Modelling/CRootBox#25]
the "test_crootbox" failed with the following error
```
"Read 2 root type parameters 
reading lai data ...
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)"
```

**Comment by xiaoranzhou** [comment]
Hey Mai, have you tried to use different parameter file? 
When I change the examples in main.cpp
`// example1(); // open parameter file, and output VTP
    // example1_wb_dgf(); // root growth inside a big box to simulate soil surface, open parameter file, and output VTP
    // example2(); // like example 1, but with put geometry
    // example3(); // more than 1 plant
    // example4(); // rhizotubes (an example for a more complex geomety)
    // example5(); // hydrotropism

    // benchmarks();

    //    if (argc>1) {
    //        cout<<"starting simulation: "<< name <<"\n";
    //        shehan_SoilCore(name, false); // put true here to export geometry
    //    } else {
    //        shehan_SoilCore(); // with default values
    //    }
    //
    // shehan_SoilCore("Anagallis_femina_Leitner_2010",true);

    // shehan_RhizoTubes("wheat",true);

    // shehan_Trenches("wheat",true);

    // example_dumux(); // tests the suggested dumux coupling

    // example_exudation();
    // shehan_ScaleElongation();
    shehan_ScaleElongation_CL();

    // example_volume();`
comment the shehan_ScaleElongation_CL();
and uncomment the example1(); 
it is working now.
