### ISSUE TITLE
Wrong root orders

### ISSUE THREAD

**Issue by sathyanarayanrao** [Plant-Root-Soil-Interactions-Modelling/CRootBox#26]
Dear Crootbox users,

I want to generate vertically oriented maize root with the following parameter files:

[Zea_mays_1_100pparam.txt](https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/files/2554239/Zea_mays_1_100pparam.txt)
[Zea_mays_1_100rparam.txt](https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/files/2554240/Zea_mays_1_100rparam.txt)

and I get the following root system which looks nice

![image](https://user-images.githubusercontent.com/37840819/48081018-5b4ce700-e1ef-11e8-9ecd-f2f4a67e09c7.png)

but if I see the rootsystem.txt
[rootsystem.txt](https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/files/2554245/rootsystem.txt)

I see some branches are of type 4 meaning 4th order root while I have only primary roots in my input paramater file. Can you please let me know, why I get 4th order roots ?

![image](https://user-images.githubusercontent.com/37840819/48081202-c8f91300-e1ef-11e8-98c5-5c7cab6c521e.png)

The code that produced the above rootsys file

[example_maize.txt](https://github.com/Plant-Root-Soil-Interactions-Modelling/CRootBox/files/2554256/example_maize.txt)

**Comment by HieuMaiTrung** [comment]
Hi, you make the point! In CRootBox the main root has 1st order. If the root system is a fibrous system, then the nodal roots are assigned as 4th order (by default).  Normally, the root parameter is only available until the 3rd order. That the reason why the default value is set to 4. Do you have root data of higher (>=4) order?  Hope that you are still happy with this setting!
